[package]
name = "bevygame"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2" }
blake3 = { version = "1.5", features=["pure"] }
bevy_ggrs = { version = "0.15" }
rand = { version = "0.8.5" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
